service: rml-crm-app-backend
# Create an optimized package for our functions
package:
  individually: true
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: prod
  region: us-east-1

  # environment:
  #  atlas_uri: ${env:ATLAS_URI}

functions:
  # Customer functions
  create:
    handler: customers.create # point to exported create function in handler.js
    events:
      - http:
          path: customers
          method: post
          cors: true
  getOne:
    handler: customers.getOne
    events:
      - http:
          path: customers/{id}
          method: get
          cors: true
  getAll:
    handler: customers.getAll
    events:
      - http:
          path: customers
          method: get
          cors: true
  update:
    handler: customers.update
    events:
      - http:
          path: customers/{id}
          method: put
          cors: true
  delete:
    handler: customers.delete
    events:
      - http:
          path: customers/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline
  # - serverless-bundle # Package our functions with Webpack
  # - serverless-dotenv-plugin
